# Generated by Django 2.0.13 on 2019-12-05 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nanubang_app', '0005_call_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete_contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buy_complete', to=settings.AUTH_USER_MODEL, verbose_name='계약자')),
                ('Room_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sell_complete', to=settings.AUTH_USER_MODEL, verbose_name='저자')),
                ('room_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nanubang_app.Room_infos')),
            ],
        ),
    ]
